[cmake] Fix incorrect linker order for vorbis/ogg
This caused errors when linking against fmt.hdll:

/usr/bin/ld: /usr/local/lib/fmt.hdll: undefined reference to `ogg_page_eos'
/usr/bin/ld: /usr/local/lib/fmt.hdll: undefined reference to `vorbis_synthesis_headerin'
/usr/bin/ld: /usr/local/lib/fmt.hdll: undefined reference to `vorbis_synthesis_trackonly'
/usr/bin/ld: /usr/local/lib/fmt.hdll: undefined reference to `ogg_page_continued'
/usr/bin/ld: /usr/local/lib/fmt.hdll: undefined reference to `ogg_sync_init'
/usr/bin/ld: /usr/local/lib/fmt.hdll: undefined reference to `ogg_sync_reset'
/usr/bin/ld: /usr/local/lib/fmt.hdll: undefined reference to `vorbis_info_clear'
/usr/bin/ld: /usr/local/lib/fmt.hdll: undefined reference to `vorbis_synthesis'
/usr/bin/ld: /usr/local/lib/fmt.hdll: undefined reference to `ogg_sync_pageseek'
/usr/bin/ld: /usr/local/lib/fmt.hdll: undefined reference to `vorbis_block_clear'
/usr/bin/ld: /usr/local/lib/fmt.hdll: undefined reference to `vorbis_synthesis_blockin'
/usr/bin/ld: /usr/local/lib/fmt.hdll: undefined reference to `ogg_page_serialno'
/usr/bin/ld: /usr/local/lib/fmt.hdll: undefined reference to `vorbis_synthesis_idheader'
/usr/bin/ld: /usr/local/lib/fmt.hdll: undefined reference to `vorbis_synthesis_init'
/usr/bin/ld: /usr/local/lib/fmt.hdll: undefined reference to `vorbis_synthesis_halfrate'
/usr/bin/ld: /usr/local/lib/fmt.hdll: undefined reference to `ogg_stream_reset_serialno'
/usr/bin/ld: /usr/local/lib/fmt.hdll: undefined reference to `ogg_stream_reset'
/usr/bin/ld: /usr/local/lib/fmt.hdll: undefined reference to `ogg_stream_packetpeek'
/usr/bin/ld: /usr/local/lib/fmt.hdll: undefined reference to `vorbis_synthesis_pcmout'
/usr/bin/ld: /usr/local/lib/fmt.hdll: undefined reference to `vorbis_packet_blocksize'
/usr/bin/ld: /usr/local/lib/fmt.hdll: undefined reference to `ogg_sync_wrote'
/usr/bin/ld: /usr/local/lib/fmt.hdll: undefined reference to `vorbis_dsp_clear'
/usr/bin/ld: /usr/local/lib/fmt.hdll: undefined reference to `vorbis_block_init'
/usr/bin/ld: /usr/local/lib/fmt.hdll: undefined reference to `vorbis_window'
/usr/bin/ld: /usr/local/lib/fmt.hdll: undefined reference to `vorbis_synthesis_restart'
/usr/bin/ld: /usr/local/lib/fmt.hdll: undefined reference to `ogg_stream_pagein'
/usr/bin/ld: /usr/local/lib/fmt.hdll: undefined reference to `vorbis_synthesis_read'
/usr/bin/ld: /usr/local/lib/fmt.hdll: undefined reference to `ogg_stream_packetout'
/usr/bin/ld: /usr/local/lib/fmt.hdll: undefined reference to `ogg_sync_buffer'
/usr/bin/ld: /usr/local/lib/fmt.hdll: undefined reference to `vorbis_info_blocksize'
/usr/bin/ld: /usr/local/lib/fmt.hdll: undefined reference to `vorbis_synthesis_halfrate_p'
/usr/bin/ld: /usr/local/lib/fmt.hdll: undefined reference to `ogg_page_granulepos'
/usr/bin/ld: /usr/local/lib/fmt.hdll: undefined reference to `vorbis_comment_init'
/usr/bin/ld: /usr/local/lib/fmt.hdll: undefined reference to `vorbis_comment_clear'
/usr/bin/ld: /usr/local/lib/fmt.hdll: undefined reference to `ogg_stream_clear'
/usr/bin/ld: /usr/local/lib/fmt.hdll: undefined reference to `ogg_page_bos'
/usr/bin/ld: /usr/local/lib/fmt.hdll: undefined reference to `ogg_stream_init'
/usr/bin/ld: /usr/local/lib/fmt.hdll: undefined reference to `vorbis_synthesis_lapout'
/usr/bin/ld: /usr/local/lib/fmt.hdll: undefined reference to `vorbis_info_init'
/usr/bin/ld: /usr/local/lib/fmt.hdll: undefined reference to `ogg_sync_clear'