Fix error/warning about implicit wmain declaration
GCC:
```
error: implicit declaration of function 'wmain'
```

MSVC:
```
warning C4013: 'wmain' undefined; assuming extern returning int
```